Adds a code of conduct
nunit/governance pull request #19
Opened 2017-06-15 21:47 UTC by rprouse

Fixes #18 

I added my email as a point of contact for violations. I can change this if people prefer. I also added a short blurb to the README as recommended by [Contributor Covenant](http://contributor-covenant.org/). While updating the README, I noticed we had a todo to add the completed documents, so I did that at the same time.

I generated the CC using their `covgen` tool, so it was trivial to add. Based on that, we could easily add the same full CC to all projects. I am fine with just a `CODE_OF_CONDUCT.md` with just a link though. If we approve this CC, I think we should decide that at the same time.

I would also like to add the **Code of Conduct** blurb to each projects `README.md` and maybe a short blurb with a link to this repository?

2017-06-15 22:29 UTC, jnm2 requested changes

2017-06-15 22:29 UTC, jnm2 commented on README.md
> +Please note that all NUnit projecst are released with a [Contributor Code of Conduct](CODE_OF_CONDUCT.md). By participating in these projects you agree to abide by its terms.
I'm not sure about the terminology of release. How about `Please note that all NUnit projects have a`?

2017-06-15 22:36 UTC, rprouse commented on README.md
> +Please note that all NUnit projecst are released with a [Contributor Code of Conduct](CODE_OF_CONDUCT.md). By participating in these projects you agree to abide by its terms.
This wording is the pluralized wording recommended at http://contributor-covenant.org/, but I am fine with the change. I will hold off on making the change until others comment.

2017-06-15 22:41 UTC, jnm2 commented on README.md
> +Please note that all NUnit projecst are released with a [Contributor Code of Conduct](CODE_OF_CONDUCT.md). By participating in these projects you agree to abide by its terms.
I didn't know they recommended that wording. In that case I have no opinion either way besides a small typo fix.

2017-06-15 22:46 UTC, rprouse commented on README.md
> +Please note that all NUnit projecst are released with a [Contributor Code of Conduct](CODE_OF_CONDUCT.md). By participating in these projects you agree to abide by its terms.
I can't even pluralize correctly without spelling it wrong :smile: I will fix.

2017-06-15 22:49 UTC, jnm2 approved these changes

2017-06-15 22:50 UTC, jnm2 commented
> I would also like to add the Code of Conduct blurb to each projects README.md and maybe a short blurb with a link to this repository?

I like this strategy.

2017-06-16 09:21 UTC, ChrisMaddock approved these changes

2017-06-16 23:00 UTC, CharliePoole commented
This looks good to me

2017-06-17 02:25 UTC, rprouse commented
We now have 4/5 approval, I am going to merge.

2017-06-17 02:25 UTC, merged